version: 2
updates:
  - package-ecosystem: swift
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '05:00'
      timezone: Asia/Tokyo
    open-pull-requests-limit: 5
    groups:
      swift-dependencies:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '05:30'
      timezone: Asia/Tokyo
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - '*'
